name: to_do
description: "Flutter ToDo app for yandex."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  intl: ^0.18.1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  sqflite: ^2.3.3+1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  surf_lint_rules: ^3.1.0

flutter:
  generate: true
  uses-material-design: true
